# Generated by Django 5.2.6 on 2025-09-28 11:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa firmy/Imię i nazwisko')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('nip', models.CharField(max_length=10, unique=True, verbose_name='NIP')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numer telefonu')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Adres e-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FiscalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model urządzenia')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Numer seryjny')),
                ('production_date', models.DateField(verbose_name='Data produkcji')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Data ostatniego przeglądu')),
                ('status', models.CharField(choices=[('active', 'Aktywna'), ('inactive', 'Niewykorzystywana'), ('serviced', 'W serwisie'), ('decommissioned', 'Wycofana')], default='active', max_length=20, verbose_name='Status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.client', verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Urządzenie fiskalne',
                'verbose_name_plural': 'Urządzenia fiskalne',
                'ordering': ['-last_service_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Opis czynności serwisowych')),
                ('service_date', models.DateTimeField(auto_now_add=True, verbose_name='Data serwisu')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='api.fiscaldevice', verbose_name='Urządzenie')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Serwisant')),
            ],
            options={
                'verbose_name': 'Wpis serwisowy',
                'verbose_name_plural': 'Wpisy serwisowe',
                'ordering': ['-service_date'],
            },
        ),
    ]
