# Generated by Django 5.2 on 2025-11-05 17:28

import api.models.clients
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa firmy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa firmy/Imię i nazwisko')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('nip', models.CharField(max_length=10, validators=[api.models.clients.validate_nip], verbose_name='NIP')),
                ('regon', models.CharField(blank=True, max_length=14, verbose_name='REGON')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numer telefonu')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Adres e-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.company')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa producenta')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='api.company')),
            ],
            options={
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FiscalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model urządzenia')),
                ('unique_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Numer unikatowy')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Numer seryjny')),
                ('sale_date', models.DateField(verbose_name='Data sprzedaży')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Data ostatniego przeglądu')),
                ('status', models.CharField(choices=[('active', 'Aktywna'), ('inactive', 'Niewykorzystywana'), ('serviced', 'W serwisie'), ('decommissioned', 'Wycofana')], default='active', max_length=20, verbose_name='Status')),
                ('operating_instructions', models.TextField(blank=True, verbose_name='Sposób użytkowania')),
                ('remarks', models.TextField(blank=True, verbose_name='Uwagi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.client', verbose_name='Właściciel')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.manufacturer', verbose_name='Marka/Producent')),
            ],
            options={
                'verbose_name': 'Urządzenie fiskalne',
                'verbose_name_plural': 'Urządzenia fiskalne',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_payment_intent', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='PLN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nazwisko')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adres e-mail')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefon służbowy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('is_company_admin', models.BooleanField(default=False, verbose_name='Admin firmy')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='api.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='Konto użytkownika')),
            ],
            options={
                'verbose_name': 'Serwisant',
                'verbose_name_plural': 'Serwisanci',
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Numer zgłoszenia')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł zgłoszenia')),
                ('description', models.TextField(verbose_name='Opis zgłoszenia')),
                ('ticket_type', models.CharField(choices=[('service', 'Przegląd'), ('reading', 'Odczyt'), ('repair', 'Naprawa'), ('other', 'Inne')], max_length=20, verbose_name='Typ zgłoszenia')),
                ('status', models.CharField(choices=[('open', 'Otwarte'), ('in_progress', 'W toku'), ('closed', 'Zamknięte')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Zaplanowano na')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data ukończenia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notatki z wykonania / Rozwiązanie')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='api.client', verbose_name='Klient')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='api.fiscaldevice', verbose_name='Urządzenie')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='api.technician', verbose_name='Przypisany serwisant')),
            ],
            options={
                'verbose_name': 'Zgłoszenie serwisowe',
                'verbose_name_plural': 'Zgłoszenia serwisowe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, verbose_name='Numer legitymacji/certyfikatu')),
                ('issue_date', models.DateField(verbose_name='Data wydania')),
                ('expiry_date', models.DateField(verbose_name='Data ważności')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='api.manufacturer')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='api.technician')),
            ],
            options={
                'verbose_name': 'Certyfikat',
                'verbose_name_plural': 'Certyfikaty',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'nip'], name='api_client_company_03d147_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'name'], name='api_client_company_8acbc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('company', 'nip'), name='unique_company_client_nip'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['company', 'name'], name='api_manufac_company_a570c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_manufacturer'),
        ),
        migrations.AddIndex(
            model_name='fiscaldevice',
            index=models.Index(fields=['owner'], name='api_fiscald_owner_i_a8c59e_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldevice',
            index=models.Index(fields=['serial_number'], name='api_fiscald_serial__21b6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stripe_session_id'], name='api_order_stripe__043f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stripe_payment_intent'], name='api_order_stripe__5e682d_idx'),
        ),
        migrations.AddIndex(
            model_name='technician',
            index=models.Index(fields=['company'], name='api_technic_company_0fc0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['status'], name='api_service_status_2d0e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['created_at'], name='api_service_created_f88365_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['manufacturer'], name='api_certifi_manufac_160d10_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['technician'], name='api_certifi_technic_20fe86_idx'),
        ),
        migrations.AddConstraint(
            model_name='certification',
            constraint=models.UniqueConstraint(fields=('technician', 'manufacturer'), name='unique_technician_manufacturer_certification'),
        ),
    ]
