# Generated by Django 5.2 on 2025-10-17 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscaldevice',
            name='production_date',
        ),
        migrations.AddField(
            model_name='fiscaldevice',
            name='brand_name',
            field=models.CharField(default='Brak', max_length=100, verbose_name='Marka urządzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscaldevice',
            name='operating_instructions',
            field=models.TextField(blank=True, verbose_name='Sposób użytkowania'),
        ),
        migrations.AddField(
            model_name='fiscaldevice',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Uwagi'),
        ),
        migrations.AddField(
            model_name='fiscaldevice',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data sprzedaży'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscaldevice',
            name='unique_number',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Numer unikatowy'),
        ),
        migrations.AlterField(
            model_name='fiscaldevice',
            name='serial_number',
            field=models.CharField(max_length=100, verbose_name='Numer seryjny'),
        ),
    ]
