# Generated by Django 5.2 on 2025-10-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_fiscaldevice_production_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='regon',
            field=models.CharField(blank=True, max_length=14, verbose_name='REGON'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa firmy/Imię i nazwisko'),
        ),
    ]
