# Generated by Django 5.2 on 2025-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='is_company_admin',
        ),
        migrations.AddField(
            model_name='technician',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator Firmy'), ('technician', 'Serwisant')], default='technician', max_length=20, verbose_name='Rola w firmie'),
        ),
    ]
