# Generated by Django 5.2 on 2025-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='resolution',
            field=models.CharField(choices=[('unresolved', 'Nierozwiązane'), ('completed', 'Zrealizowane pomyślnie'), ('failed', 'Niezrealizowane - nie udało się'), ('cancelled', 'Anulowane przez klienta')], default='unresolved', max_length=20, verbose_name='Wynik rozwiązania'),
        ),
    ]
