# Generated by Django 5.2 on 2025-11-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_serviceticket_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='scheduled_for',
            field=models.DateField(blank=True, null=True, verbose_name='Zaplanowano na'),
        ),
    ]
