# Generated by Django 5.2 on 2025-11-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_serviceticket_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Szerokość geograficzna'),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Długość geograficzna'),
        ),
    ]
