# Generated by Django 5.2 on 2025-12-02 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name='Data zdarzenia')),
                ('action_type', models.CharField(choices=[('DEVICE_CREATED', 'Utworzono urządzenie'), ('SERVICE_PERFORMED', 'Wykonano przegląd'), ('TICKET_COMPLETED', 'Zakończono zlecenie'), ('STATUS_CHANGED', 'Zmieniono status')], max_length=50, verbose_name='Rodzaj akcji')),
                ('description', models.TextField(verbose_name='Opis zdarzenia')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Wykonane przez')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='api.fiscaldevice', verbose_name='Urządzenie')),
            ],
            options={
                'verbose_name': 'Wpis historii urządzenia',
                'verbose_name_plural': 'Wpisy historii urządzeń',
                'ordering': ['-event_date'],
            },
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
