# Generated by Django 5.2 on 2025-12-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_devicehistoryentry_delete_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehistoryentry',
            name='action_type',
            field=models.CharField(choices=[('DEVICE_CREATED', 'Utworzono urządzenie'), ('SERVICE_PERFORMED', 'Wykonano przegląd'), ('TICKET_COMPLETED', 'Zakończono zlecenie'), ('TICKET_CREATED', 'Utworzono zlecenie'), ('STATUS_CHANGED', 'Zmieniono status')], max_length=50, verbose_name='Rodzaj akcji'),
        ),
    ]
